import type { CharacterId, CharacterProfile, FocusAction, SceneScript, StoryArc } from "../types";

export const CHARACTERS: Record<CharacterId, CharacterProfile> = {
  rina: {
    id: "rina",
    name: "璃奈",
    role: "温柔前辈",
    tag: "基本面主线",
    color: "pink",
    intro: "会把研报贴上粉色便签，也会认真盯着你的小金库。",
  },
  misaki: {
    id: "misaki",
    name: "美咲",
    role: "元气量化",
    tag: "短线波动线",
    color: "blue",
    intro: "拿着平板冲进会议室，最喜欢把概率说成心跳。",
  },
  mei: {
    id: "mei",
    name: "芽衣",
    role: "冷静宏观",
    tag: "周期策略线",
    color: "lavender",
    intro: "看起来很安静，但总能在大家慌乱前标出拐点。",
  },
};

export const STORY_ARCS: StoryArc[] = [
  {
    characterId: "rina",
    title: "序章：粉色便利贴",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "元气",
    line: "你在年初的投研部工位醒来，屏幕旁贴着一张粉色便利贴：这次的小金库，由我来监督你哦。",
    mission: "璃奈把四张心动情报卡排在桌上。选一张，再安排本话日程，开始重生路线。",
  },
  {
    characterId: "rina",
    title: "第一话：房租与奶茶预算",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "认真",
    line: "房租、通勤卡和奶茶预算同时报警。璃奈敲了敲你的桌面：先让账户活下来，再谈帅气登场吧。",
    mission: "本话选择会影响你的闪耀度，也会影响今天还能不能准时下班。",
  },
  {
    characterId: "misaki",
    title: "第二话：午休研报会",
    speaker: "美咲",
    role: "买方研究员",
    mood: "俏皮",
    line: "午休的咖啡还没凉，美咲就把一叠研报推过来：猜对本月主线的话，我请你吃甜点。",
    mission: "四张卡都很可爱，但真正的闪光路线藏在成交额和涨幅排名后面。",
  },
  {
    characterId: "rina",
    title: "第三话：雨夜加班图",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "温柔",
    line: "雨点敲着玻璃，璃奈把外套搭在椅背上：今晚就当是我们的秘密作战会议吧。",
    mission: "选择本月赛道，决定你是继续补表格，还是进入璃奈的核心讨论。",
  },
  {
    characterId: "mei",
    title: "第四话：路演作战",
    speaker: "芽衣",
    role: "宏观策略师",
    mood: "沉着",
    line: "部门路演就要开始了。芽衣推了推眼镜：能把市场讲清楚的人，才配站在聚光灯下。",
    mission: "收益会影响大家愿不愿意听完你的台词，复盘理由也会留下记录。",
  },
  {
    characterId: "rina",
    title: "第五话：末班车约定",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "害羞",
    line: "末班车里很安静。璃奈望着窗外，小声问：如果这次真的能改变未来，你会记得今天的约定吗？",
    mission: "本话情报会拉开分歧：追热点、看基本面，还是相信那条心跳加速的线索。",
  },
  {
    characterId: "misaki",
    title: "第六话：夏日中场复盘",
    speaker: "美咲",
    role: "买方研究员",
    mood: "兴奋",
    line: "半年过去，市场把很多人的自信晒化了。美咲托着下巴：所以，你靠的是重生记忆，还是喜欢她的直觉？",
    mission: "用一笔选择回答她：这条路线到底是奇迹，还是可以复盘的判断。",
  },
  {
    characterId: "mei",
    title: "第七话：闪耀发表会",
    speaker: "芽衣",
    role: "宏观策略师",
    mood: "观察",
    line: "发表会的灯亮起来。芽衣把你的账户曲线标上记号：这条线，开始有主角感了。",
    mission: "选对了，你从边缘座位进入主线。选错了，明天继续改演示稿。",
  },
  {
    characterId: "rina",
    title: "第八话：璃奈的深夜电话",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "在意",
    line: "电话那头停顿很久。璃奈说：这次我不替你选，但我会看着你的答案。",
    mission: "四个标的背后是四种分支，收益只是最直白的好感反馈。",
  },
  {
    characterId: "misaki",
    title: "第九话：风口心跳战",
    speaker: "美咲",
    role: "买方研究员",
    mood: "高涨",
    line: "所有群都在刷同一个方向，所有人都觉得自己是主角。美咲眨了眨眼：你也要冲进这段剧情吗？",
    mission: "在喧嚣里选择：跟随市场、逆向下注，还是相信成交额暴露出的真相。",
  },
  {
    characterId: "mei",
    title: "第十话：年末排名战",
    speaker: "芽衣",
    role: "宏观策略师",
    mood: "紧张",
    line: "年末排名开始倒计时。芽衣难得露出笑意：有人求稳，有人梭哈，而你还没有解锁最终图鉴。",
    mission: "这次选择会决定结局基调：闪耀研究员、可靠打工人，还是疲劳值爆表。",
  },
  {
    characterId: "rina",
    title: "终章：收盘后的约定",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "心动",
    line: "最后一个月，城市灯光像一张温柔的 K 线图。璃奈看着你：不要只告诉我赚了多少，也告诉我你想进入哪条结局线。",
    mission: "完成最后一次选择，结算小金库、闪耀度、疲劳值和三位女主好感。",
  },
];

export const SCENE_SCRIPTS: SceneScript[] = [
  {
    id: "demo-2025-prologue",
    monthIndex: 0,
    title: "序章：粉色便利贴",
    defaultCharacterId: "rina",
    nodes: [
      {
        type: "line",
        characterId: "rina",
        speaker: "璃奈",
        role: "投研部前辈",
        mood: "元气",
        pose: "smile",
        bg: "research-room",
        bgm: "morning-loop",
        text: "你原本是现实世界的股票研究员，凌晨还在复盘历史行情。再睁眼时，自己已经坐在二次元投研部的工位前。",
        prompt: "点击继续，确认这场重生的开端。",
      },
      {
        type: "line",
        characterId: "rina",
        speaker: "璃奈",
        role: "投研部前辈",
        mood: "温柔",
        pose: "soft",
        bg: "research-room",
        bgm: "morning-loop",
        text: "璃奈站在你桌边，像早就等着你醒来：欢迎回到行情开始之前。这里会把历史行情重新排到你面前，像一间只为复盘存在的投研部。",
      },
      {
        type: "line",
        characterId: "rina",
        speaker: "璃奈",
        role: "基本面研究员",
        mood: "认真",
        pose: "thinking",
        bg: "research-room",
        bgm: "morning-loop",
        text: "她把一杯热咖啡推到你手边：你记得一些历史大方向，但只背答案会让世界线偏移。把记忆整理成研究逻辑，路线才会稳定。",
      },
      {
        type: "line",
        characterId: "misaki",
        speaker: "美咲",
        role: "元气量化",
        mood: "俏皮",
        pose: "excited",
        bg: "research-room",
        bgm: "morning-loop",
        text: "美咲抱着平板冲进会议室：早盘信号来了！成交额、换手、波动率全都在闪。你以前写研报，现在要用研报在二次元活下去。",
      },
      {
        type: "line",
        characterId: "misaki",
        speaker: "美咲",
        role: "资金信号研究员",
        mood: "高涨",
        pose: "focused",
        bg: "research-room",
        bgm: "morning-loop",
        text: "她点开四条候选线索：有事件驱动，也有资金抱团。别只问哪只涨得最多，要先判断哪条逻辑能从月初延续到月末。",
      },
      {
        type: "line",
        characterId: "mei",
        speaker: "芽衣",
        role: "宏观策略师",
        mood: "沉着",
        pose: "serious",
        bg: "briefing-room",
        bgm: "morning-loop",
        text: "芽衣在会议室白板上圈出月初和月末两个日期：这是历史切片。价格会复现，你的介入也会改变市场情绪和中间路径。",
      },
      {
        type: "line",
        characterId: "mei",
        speaker: "芽衣",
        role: "宏观策略师",
        mood: "观察",
        pose: "neutral",
        bg: "briefing-room",
        bgm: "morning-loop",
        text: "她补上一行小字：行业景气、政策边际、资金拥挤度，三者缺一不可。历史给你答案以前，市场会先考你的解释能力。",
      },
      {
        type: "line",
        characterId: "rina",
        speaker: "璃奈",
        role: "基本面研究员",
        mood: "认真",
        pose: "thinking",
        bg: "briefing-room",
        bgm: "morning-loop",
        text: "璃奈翻开笔记：我们先做第一份投研纪要。你的小金库只有一万元，但真正要积累的是可信的研究档案。",
      },
      {
        type: "line",
        characterId: "misaki",
        speaker: "美咲",
        role: "资金信号研究员",
        mood: "俏皮",
        pose: "excited",
        bg: "briefing-room",
        bgm: "morning-loop",
        text: "美咲把平板转向你：我负责资金信号。谁在放量，谁被市场反复确认，谁只是短暂噪音，我都会标出来。",
      },
      {
        type: "line",
        characterId: "mei",
        speaker: "芽衣",
        role: "宏观策略师",
        mood: "沉着",
        pose: "serious",
        bg: "briefing-room",
        bgm: "morning-loop",
        text: "芽衣轻轻敲了敲杯沿：我负责周期和风险。别只盯涨幅，能说清上涨原因，才有资格入场。",
      },
      {
        type: "line",
        characterId: "rina",
        speaker: "璃奈",
        role: "投研部前辈",
        mood: "温柔",
        pose: "smile",
        bg: "briefing-room",
        bgm: "morning-loop",
        text: "璃奈把四张情报卡排成一列：先决定今天怎么安排，再选一张你愿意负责到底的卡。净值会结算，但研究札记也会留下。",
        prompt: "下一步会进入本月情报会。",
      },
      {
        type: "stockRound",
        prompt: "安排本话日程，然后选择一张心动情报卡。",
        bg: "briefing-room",
        briefTitle: "第一次研究会：历史切片的四条线索",
        briefs: [
          {
            characterId: "rina",
            label: "基本面",
            text: "先看行业能不能解释月内上涨，避免只被名字和题材带走。",
          },
          {
            characterId: "misaki",
            label: "资金面",
            text: "成交活跃排名越靠前，越可能说明资金已经开始投票。",
          },
          {
            characterId: "mei",
            label: "宏观风控",
            text: "如果逻辑只在月初成立，月末兑现前就可能被风险反噬。",
          },
        ],
      },
      {
        type: "line",
        characterId: "misaki",
        speaker: "美咲",
        role: "元气量化",
        mood: "高涨",
        pose: "excited",
        bg: "night-cafe",
        bgm: "result-loop",
        text: "夜里的咖啡店还亮着灯。美咲把结算曲线投到平板上：看，这就是你的第一条存档分支！收益会留下数字，选择理由更值得复盘。",
      },
      {
        type: "line",
        characterId: "misaki",
        speaker: "美咲",
        role: "资金信号研究员",
        mood: "观察",
        pose: "focused",
        bg: "night-cafe",
        bgm: "result-loop",
        text: "她把成交活跃排名和涨幅排名并排放着：选对了，说明信号和主线共振。没选对，也能知道是哪一层假设先断掉。",
      },
      {
        type: "line",
        characterId: "mei",
        speaker: "芽衣",
        role: "宏观策略师",
        mood: "观察",
        pose: "serious",
        bg: "night-cafe",
        bgm: "result-loop",
        text: "芽衣低头记录：收益、疲劳、好感都已经变化。下一话开始，每个月都会变成一段金融事件，有行情、有判断，也有代价。",
      },
      {
        type: "line",
        characterId: "mei",
        speaker: "芽衣",
        role: "宏观策略师",
        mood: "沉着",
        pose: "soft",
        bg: "night-cafe",
        bgm: "result-loop",
        text: "她推来一张新的表格：还要记录世界线偏移。你越依赖未来记忆，偏移越快。你越能自洽地解释市场，偏移越慢。",
      },
      {
        type: "line",
        characterId: "rina",
        speaker: "璃奈",
        role: "投研部前辈",
        mood: "心动",
        pose: "soft",
        bg: "night-cafe",
        bgm: "result-loop",
        text: "璃奈轻轻合上笔记本：第一话结束。要继续的话，就把这次研究判断带进下一月吧。这个世界会奖励收益，也会记住你怎么解释收益。",
      },
      {
        type: "line",
        characterId: "rina",
        speaker: "璃奈",
        role: "基本面研究员",
        mood: "温柔",
        pose: "smile",
        bg: "night-cafe",
        bgm: "result-loop",
        text: "她看着窗外的城市灯光，小声补了一句：如果你真的能把历史重新研究一遍，也许我们能知道你为什么会来到这里。",
        prompt: "点击进入下一话。",
      },
    ],
  },
];

export const FOCUS_ACTIONS: FocusAction[] = [
  {
    id: "research",
    label: "熬夜研报",
    icon: "✦",
    short: "收益修正 +1.5%",
    detail: "重新整理线索和假设。收益有额外修正，疲劳值会上升。",
    returnBonus: 0.015,
    reputationDelta: 4,
    fatigueDelta: 8,
    affectionDelta: 1,
  },
  {
    id: "date",
    label: "茶歇复盘",
    icon: "♡",
    short: "好感 +7",
    detail: "把晚上的复盘放到咖啡店里聊。收益没有加成，当前角色会更信任你。",
    returnBonus: 0,
    reputationDelta: 1,
    fatigueDelta: -3,
    affectionDelta: 7,
  },
  {
    id: "risk",
    label: "仓位纪律",
    icon: "◇",
    short: "疲劳 -9",
    detail: "少做一页演示稿，多睡一小时。执行更稳，但会放弃一部分激进收益。",
    returnBonus: -0.005,
    reputationDelta: 2,
    fatigueDelta: -9,
    affectionDelta: 2,
  },
];

export const SIGNAL_TYPES = ["事件驱动", "业绩反转", "资金抱团", "政策风口", "产业链暗线", "高波动机会"];
